# Generated by Django 4.2.2 on 2023-06-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('autores', models.TextField(null=True)),
                ('total_paginas', models.IntegerField(default=0)),
                ('data_pub', models.DateTimeField()),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp1.editora')),
            ],
        ),
    ]
